version: 0.2
env:
  variables:
    CUDA_HOME: "/usr/local/cuda"
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - apt-get update && apt-get install -y cmake
  pre_build:
    commands:
      - echo "Installing CUDA Toolkit"
      - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
      - dpkg -i cuda-keyring_1.0-1_all.deb
      - apt-get update
      - apt-get install -y cuda-toolkit-11-8
      - export PATH=/usr/local/cuda-11.8/bin${PATH:+:${PATH}}
      - export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      - nvcc --version
      - nvidia-smi
  build:
    commands:
      - echo "Uploading to Hugging Face"
      - pip install huggingface_hub
      - python - <<EOF
        from huggingface_hub import login, upload_folder
        login(token="${HF_TOKEN}")
        upload_folder(
            folder_path="models",
            path_in_repo="",
            repo_id="NickLamb/OpenROAD-7B-Instruct",
            repo_type="model"
        )
        EOF

artifacts:
  files:
    - '**/*'
